#!/bin/bash

# Colors
Red='\e[0;31m'  # Kept color names as requested
BRed='\e[1;31m'  # Kept color names as requested
BIRed='\e[1;91m'  # Kept color names as requested
Gre='\e[0;32m'  # Kept color names as requested
BGre='\e[1;32m'  # Kept color names as requested
BBlu='\e[1;34m'  # Kept color names as requested
BWhi='\e[1;37m'  # Kept color names as requested
RCol='\e[0m'  # Kept color names as requested

codename="$(grep UBUNTU_CODENAME /etc/os-release | cut -d = -f 2)"
osname="$(grep -E '="?Ubuntu"?$' /etc/os-release | cut -d = -f 2)"

if [[ "$codename" == "focal" && $osname == \"Ubuntu\" ]]
then
  bash src/ubuntu-20.04.sh "$@"  # Changed to use double quotes for consistency
else
  echo -e "${Red}
------------------------------------------------------------------
Sorry, Script is only for Ubuntu ${BWhi}20.04, 21.04, 21.10, 22.04, 22.10, 23.04 & 23.10 & 24.04${Red} Only
Exiting...
------------------------------------------------------------------
${RCol}"
  exit 1
fi
